### ISSUE TITLE
Request: Add the ability to customize the Images being used as bit icons

### ISSUE THREAD

**Issue by Ayumix3** [typeou/karasubonk#8]
I think it would be nice to let people customize the images being used as bit icons. Currently you can't do that in any ways, even replacing the files inside the "resources/app/throws" path does not work, as they get reloaded on app startup.

**Comment by typeou** [comment]
This is possible through the "BITS" tab in the "Bonk Images" page. Each bit type has a green "+" that allows a new image to be selected.

![image](https://github.com/typeou/karasubonk/assets/24858694/fded1089-d4ac-4c30-a57b-79bac9b0fb73)
